### ISSUE TITLE
Ubuntu 22.04 - open "./w64system/w64system000": no such file or directory

### ISSUE THREAD

**Issue by Slach** [wetorrent/wetorrent#1]
after succesfull build and install
```bash
go install github.com/wetorrent/wetorrent@latest
~/go/bin/wetorrent
```

return
```
{
    "ip": "xxx",
    "network": "xxx",
    "version": "IPv4",
    "city": "Yerevan",
    "region": "Yerevan",
    "region_code": "ER",
    "country": "AM",
    "country_name": "Armenia",
    "country_code": "AM",
    "country_code_iso3": "ARM",
    "country_capital": "Yerevan",
    "country_tld": ".am",
    "continent_code": "AS",
    "in_eu": false,
    "postal": null,
    "latitude": 40.1817,
    "longitude": 44.5099,
    "timezone": "Asia/Yerevan",
    "utc_offset": "+0400",
    "country_calling_code": "+374",
    "currency": "AMD",
    "currency_name": "Dram",
    "languages": "hy",
    "country_area": 29800.0,
    "country_population": 2951776,
    "asn": "AS44395",
    "org": "Ucom CJSC"
}
2023/02/04 14:35:31 open ./w64system/w64system000: no such file or directory
```

how to fix this error?

**Comment by bon5642** [comment]
Do you have ./w64system/w64system000 in the repo directory?

**Comment by Slach** [comment]
after
```bash
mv ~/go/bin/wetorrent /home/slach/go/pkg/mod/github.com/wetorrent/wetorrent@v0.0.0-20230203162801-8100a5787408/
cd /home/slach/go/pkg/mod/github.com/wetorrent/wetorrent@v0.0.0-20230203162801-8100a5787408/
chmod +w -R .
```
this return another error

```
2023/02/04 15:30:16 Fyne error:  failed to read theme variant from D-Bus
2023/02/04 15:30:16   Cause: Name "org.freedesktop.portal.Desktop" does not exist
2023/02/04 15:30:16   At: /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/app/app_xdg.go:51
2023/02/04 15:30:16 PlatformError: X11: The DISPLAY environment variable is missing
panic: NotInitialized: The GLFW library is not initialized

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc0001c7ce0?})
        /home/slach/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:174 +0x1d9
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        /home/slach/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/error.go:185
github.com/go-gl/glfw/v3.3/glfw.CreateStandardCursor(0xfe1ba0?)
        /home/slach/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/input.go:530 +0x45
fyne.io/fyne/v2/internal/driver/glfw.initCursors()
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window_desktop.go:47 +0x5f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW.func1()
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop_desktop.go:27 +0x54
sync.(*Once).doSlow(0x203000?, 0x203000?)
        /usr/lib/go-1.19/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /usr/lib/go-1.19/src/sync/once.go:65
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).initGLFW(0xc0001c7df8?)
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop_desktop.go:16 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1()
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:937 +0x4a
fyne.io/fyne/v2/internal/driver/glfw.runOnMain(0xc000481620)
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/loop.go:61 +0x11d
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow(0xc000324000, {0x1117683, 0x9}, 0x1)
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:936 +0xe5
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).CreateWindow(0x12cc148?, {0x1117683?, 0x0?})
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/internal/driver/glfw/window.go:928 +0x25
fyne.io/fyne/v2/app.(*fyneApp).NewWindow(0x0?, {0x1117683?, 0x191fa80?})
        /home/slach/go/pkg/mod/fyne.io/fyne/v2@v2.3.0/app/app.go:68 +0x26
main.main()
        /home/slach/go/pkg/mod/github.com/wetorrent/wetorrent@v0.0.0-20230203162801-8100a5787408/main.go:40 +0xcf
```

**Comment by bon5642** [comment]
First you should have cloned outside the go/bin.
Second did you install a C compiler (to handle graphics drivers) and graphics drivers?

More information on how to do this, depending on your operating system, can be found here: https://developer.fyne.io/started/
